mysite/blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<blog_slug>[-\w]+)/$', views.content, name='content'))

mysite/mysite/blog/urls.py
from django.conf.urls import patterns, url
from mysite.blog.views import BlogListView, CategoryListView, BlogDetailView

POSTS_PER_PAGE = 20

urlpatterns = patterns('',
    # With class-based views we can only query the database for slugs using
    # a class method
    url(r'^$',
        BlogListView.as_view(paginate_by=POSTS_PER_PAGE),
        name="index",
        ),

    url(r'^category/(?P<category_slug>[-\w]+)$',
        CategoryListView.as_view(paginate_by=POSTS_PER_PAGE),
        name="categorized",
        ),

    url(r'^(?P<slug>[-\w]+)$',
        BlogDetailView.as_view(),
        name="content",
        ),

    url(r'^page(?P<page>[0-9]+)$',
        BlogListView.as_view(paginate_by=POSTS_PER_PAGE),
        name="paginated",
        ),
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from mysite.blog.models import Blog, Category
from filebrowser.sites import site
import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
#    url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'mysite.home.views.homepage', name="home"),
    url(r'^blogs/', include('mysite.blog.urls', namespace="blog")),
    url(r'^data/', include('mysite.data.urls', namespace="data")),
    url(r'^wedding/', 'mysite.wedding.views.view_wedding', name='wedding'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/blog/models.py
from django.db import models
from django.contrib.auth.models import User

from markdown import markdown

class Category(models.Model):
    '''
    Class for blog categories.
    '''
    
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = "categories"
        ordering = ["title"]
    
    def __unicode__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog-categorized', kwargs={"category_slug": self.slug})
    
class Blog(models.Model):
    '''
    Class for blog posts.
    '''
    
    class Meta:
        ordering = ["-pub_date"]
    
    title = models.CharField(max_length=300)
    slug = models.SlugField(unique=True)
    lang = models.CharField(default='en', max_length=2)
    author = models.ForeignKey(User, blank=True, null=True)
    body = models.TextField(help_text="Use markdown")
    tease = models.TextField(blank=True,
                             help_text="Use markdown")
    categories = models.ManyToManyField(Category)
    pub_date = models.DateTimeField('Date Published')
    image = models.ImageField(upload_to='blog_images', blank=True)
    script = models.TextField(help_text="Add scripts here", blank=True)
    allow_comments = models.BooleanField(default=False)
    highlight = models.BooleanField(default=True,
                                    help_text='Highlight this post on the front page')
    body_html = models.TextField(help_text="Valid html (not markup) for the templates", editable=False)
    tease_html = models.TextField(blank=True, editable=False)
    
    def __unicode__(self):
        return self.title

    def save(self):
        self.body_html = markdown(self.body)
        self.tease_html = markdown(self.tease)
        super(Blog, self).save()
    
    def list_categories(self):
        return ', '.join([category.title for category in self.categories.all()])
    list_categories.short_description = 'Categories'
    
    def get_absolute_url(self):
        return reverse('blog', kwargs={"slug": self.slug})

mysite/blog/views.py
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from blog.models import Blog, Category

def index(request):
    list_categories = Category.objects.all()
    years = []
    
    blogs = Blog.objects.order_by('-pub_date')
    paginator = Paginator(blogs, 25)
    page = request.GET.get('page')
    try:
        list_blogs = paginator.page(page)
    except PageNotAnInteger:
        list_blogs = paginator.page(1)
    except EmptyPage:
        list_blogs = paginator.page(paginator.num_pages)
           
    context = RequestContext(request,
                             {'list_blogs':list_blogs,
                              'list_categories':list_categories})
    return render(request, 'blog/blog_index.html', context)

def content(request, blog_slug):
    list_blogs = Blog.objects.order_by('-pub_date')
    blog = get_object_or_404(Blog, slug=blog_slug)
    return render(request, 'blog/blog_content.html',
                  {'blog':blog,
                   'list_blogs':list_blogs
                   })

mysite/mysite/blog/views.py
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from mysite.blog.models import Blog, Category

class BlogListView(ListView):
    queryset = Blog.objects.all()
    template_name = "blog/blog_index.html"
    context_object_name = 'list_blogs'
    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        context['list_categories'] = Category.objects.all()
        context['selected_category'] = None
        return context

class CategoryListView(BlogListView):
    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['selected_category'] = self.kwargs['category_slug']
        return context

    def get_queryset(self):
        selected_category = get_object_or_404(Category, slug=self.kwargs['category_slug'])
        return selected_category.blog_set.all()


class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog/blog_content.html"
    context_object_name = 'blog'
    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['list_categories'] = Category.objects.all()
        context['list_blogs'] = Blog.objects.order_by('-pub_date')
        return context

mysite/mysite/blog/templates/blog/blog_content.html
{% extends "blog/blog_index.html" %}
{% load staticfiles %}

{% block extralinks %}
<link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/atelier-forest.light.min.css">
{% endblock %}

{% block main_content %}
{% if blog %}
<div class="blog-content">
	<div class="blog-title">
		<h3>{{ blog.title }}</h3>
		<p>
			{{ blog.pub_date }}
		</p>
		<div class="row">
			<div class="col-sm-6">
				{% if blog.categories.all %}
				{% for category in blog.categories.all %}
				<span class="label-primary" href="#"> {{ category.title }} </span>
				{% endfor %}
				{% else %}
				<span class="label" href="#"> 无分类 </span>
				{% endif %}
			</div>
			<div class="col-sm-6">
				<div class="share">
					<a href="http://share.renren.com/share/buttonshare.do?link=http://www.zengxiaohan.com{% url 'blog:content' blog.slug %}"> <img src="{% static 'home/assets/renren-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="http://service.weibo.com/share/share.php?url=http://www.zengxiaohan.com{% url 'blog:content' blog.slug %}&appkey=&title={{ blog.title }}&pic={{ blog.image }}&ralateUid=&language=zh_cn"> <img src="{% static 'home/assets/weibo-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="https://www.facebook.com/sharer/sharer.php?u=http://www.zengxiaohan.com{% url 'blog:content' blog.slug %}&display=popup"> <img src="{% static 'home/assets/facebook-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="https://twitter.com/intent/tweet?text=@XiaohanZeng {{ blog.title }}&url=http://www.zengxiaohan.com{% url 'blog:content' blog.slug %}"> <img src="{% static 'home/assets/twitter-logo-dark.png' %}" class="social_network_logo small"/> </a>
				</div>
			</div>
		</div>
	</div>
	<div class="blog-body">
		{% if blog.image %}
		<img src="{{ MEDIA_URL }}{{ blog.image }}" class="blog-image"/>
		{% endif %}
		<p id="blog-body">
			{{ blog.body_html|safe }}
		</p>
		{% if blog.script %}
		<p id="blog-script">
			{{ blog.script|safe }}
		</p>
		{% endif %}
	</div>
	<div class="blog-comments" id="disqus_thread"></div>
</div>
<noscript>
	Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
{% endif %}
{% endblock %}
{% block scripts %}
<script type="text/javascript">
	var disqus_shortname = 'zengxiaohan';
	(function() {
		var dsq = document.createElement('script');
		dsq.type = 'text/javascript';
		dsq.async = true;
		dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	})(); 
</script>
<script src="http://yandex.st/highlightjs/8.0/highlight.min.js"></script>
<script>
	$(document).ready(function() {
		$('pre').each(function(i, e) {
			hljs.highlightBlock(e);
		});
	}); 
</script>
{% endblock %}

mysite/mysite/blog/templates/blog/blog_index.html
{% extends "base_index.html" %}
{% load staticfiles %}
{% block extralinks %}
{% endblock %}
{% block menu %}
<div class="container">
	<div class="bs-sidebar affix">
		<div class="sidebar-heading">
			<h4>博文目录</h4>
		</div>
		<div class="sidebar-content">
			<ul class="nav">
				<li class="active">
					<span class="badge pull-right">{{ list_blogs|length }}</span>
					<a href="{% url 'blog:index' %}"> <h4>所有博文</h4> </a>
				</li>
				{% if list_categories %}
				{% for category in list_categories %}
				<li>
					<a href="{% url 'blog:categorized' category_slug=category.slug %}"> <h4> {{ category.title }} </h4></a>
				</li>
				{% endfor %}
				{% else %}
				<li>
					无分类
				</li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>

{% endblock %}

{% block main_content %}
{% if list_blogs %}
<div class="container" id="masonry-content">
	<!-- <div class="pagination">
	<span class="step-links"> {% if list_blogs.has_previous %} <a href="?page={{ list_blogs.previous_page_number }}"> previous </a> {% endif %} <span class="current"> Page {{ list_blogs.number }} of {{ list_blogs.paginator.num_pages }} </span> {% if list_blogs.has_next %} <a href="?page={{ list_blogs.next_page_number }}"> next </a> {% endif %} </span>
	</div> -->

	{% for blog in list_blogs %}
	<div class="blog item">
		<div>
			<a href="{% url 'blog:content' blog.slug %}"><h3>{{ blog.title }}</h3></a>
		</div>
		<p>
			{{ blog.pub_date }}
		</p>
		<div class="row">
			<div class="col-sm-6">
				{% with categories=blog.categories.all %}
				{% if categories %}
				{% for category in categories %}
				<span class="label-primary" href="#"> {{ category.title }} </span>
				{% endfor %}
				{% else %}
				<span class="label" href="#"> 无分类 </span>
				{% endif %}
				{% endwith %}

			</div>
			<div class="col-sm-6">
				<div class="share">
					<a href="http://share.renren.com/share/buttonshare.do?link=http://www.zengxiaohan.com{% url 'blog:content' blog.slug %}"> <img src="{% static 'home/assets/renren-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="http://service.weibo.com/share/share.php?url=http://www.zengxiaohan.com{% url 'blog:content' blog.slug %}&appkey=&title={{ blog.title }}&pic={{ blog.image }}&ralateUid=&language=zh_cn"> <img src="{% static 'home/assets/weibo-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="https://www.facebook.com/sharer/sharer.php?u=http://www.zengxiaohan.com{% url 'blog:content' blog.slug %}&display=popup"> <img src="{% static 'home/assets/facebook-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="https://twitter.com/intent/tweet?text=@XiaohanZeng {{ blog.title }}&url=http://www.zengxiaohan.com{% url 'blog:content' blog.slug %}"> <img src="{% static 'home/assets/twitter-logo-dark.png' %}" class="social_network_logo small"/> </a>
				</div>
			</div>
		</div>

		{% if blog.image %}
		<hr>
		<img src="{{ MEDIA_URL }}{{ blog.image }}" class="blog-tease-image"/>
		{% endif %}
		<div class="blog-tease">
			<p>
				{{ blog.tease }}
			</p>
		</div>

	</div>
	{% endfor %}
	{% else %}
	<li>
		No blogs are available.
	</li>
	{% endif %}
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'home/js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'home/js/imagesloaded.pkgd.min.js' %}"></script>
<script type='text/javascript'>
	var $container = $('#masonry-content');
	// Resolve image loading issue
	$container.imagesLoaded(function() {
		$container.masonry({
			//columnWidth:200,
			itemSelector : '.item'
		});
	}); 
</script>
{% endblock %}