mysite/blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<blog_slug>[-\w]+)/$', views.content, name='content'))

mysite/mysite/data/urls.py
from django.conf.urls import patterns, url
from mysite.data.views import DataListView, DataCategoryListView, DataDetailView

POSTS_PER_PAGE = 20

urlpatterns = patterns('',
    # With class-based views we can only query the database for slugs using
    # a class method
    url(r'^$',
        DataListView.as_view(paginate_by=POSTS_PER_PAGE),
        name="index",
        ),

    url(r'^category/(?P<category_slug>[-\w]+)$',
        DataCategoryListView.as_view(paginate_by=POSTS_PER_PAGE),
        name="categorized",
        ),

    url(r'^(?P<slug>[-\w]+)$',
        DataDetailView.as_view(),
        name="content",
        ),

    url(r'^page(?P<page>[0-9]+)$',
        DataListView.as_view(paginate_by=POSTS_PER_PAGE),
        name="paginated",
        ),
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from mysite.blog.models import Blog, Category
from filebrowser.sites import site
import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
#    url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'mysite.home.views.homepage', name="home"),
    url(r'^blogs/', include('mysite.blog.urls', namespace="blog")),
    url(r'^data/', include('mysite.data.urls', namespace="data")),
    url(r'^wedding/', 'mysite.wedding.views.view_wedding', name='wedding'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/data/models.py
from django.db import models
from mysite.common.models import CommonPost, CommonCategory

class DataCategory(CommonCategory):
    '''
    Class for data categories.
    '''
    
    class Meta:
        verbose_name_plural = "data categories"
    
    def get_absolute_url(self):
        return reverse('data-categorized', kwargs={"category_slug": self.slug})
    
class Data(CommonPost):
    '''
    Class for Data posts.
    '''
    
    categories = models.ManyToManyField(DataCategory)
    code = models.TextField(help_text="Add code here", blank=True)
    
    def list_categories(self):
        return ', '.join([category.title for category in self.categories.all()])
    list_categories.short_description = 'Categories'
    
    def get_absolute_url(self):
        return reverse('data', kwargs={"slug": self.slug})

mysite/mysite/data/views.py
from django.template import RequestContext, loader
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from mysite.data.models import Data, DataCategory

class DataListView(ListView):
    queryset = Data.objects.all()
    template_name = "data/data_index.html"
    context_object_name = 'list_datas'
    def get_context_data(self, **kwargs):
        context = super(DataListView, self).get_context_data(**kwargs)
        context['list_categories'] = DataCategory.objects.all()
        context['selected_category'] = None
        return context

class DataCategoryListView(DataListView):
    def get_context_data(self, **kwargs):
        context = super(DataCategoryListView, self).get_context_data(**kwargs)
        context['selected_category'] = self.kwargs['category_slug']
        return context

    def get_queryset(self):
        selected_category = get_object_or_404(DataCategory, slug=self.kwargs['category_slug'])
        return selected_category.data_set.all()


class DataDetailView(DetailView):
    model = Data
    template_name = "data/data_content.html"
    context_object_name = 'data'
    def get_context_data(self, **kwargs):
        context = super(DataDetailView, self).get_context_data(**kwargs)
        context['list_categories'] = DataCategory.objects.all()
        context['list_datas'] = Data.objects.order_by('-pub_date')
        return context

mysite/mysite/data/templates/data/data_content.html
{% extends "data/data_index.html" %}
{% load staticfiles %}
{% block extralinks %}
<link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/atelier-forest.light.min.css">
{% endblock %}
{% block content %}
{% if data %}
<div class="main-content-data">
	<div class="container data-content">
		<div class="data-content-text">
			<div class="data-title">
				<h1>{{ data.title }}</h1>
				<p>
					{{ data.pub_date }}
				</p>
				{% if data.categories.all %}
				{% for category in data.categories.all %}
				<span class="label-primary" href="#"> {{ category.title }} </span>
				{% endfor %}
				{% else %}
				<span class="label" href="#"> 无分类 </span>
				{% endif %}
				<div class="share">
					<a href="http://share.renren.com/share/buttonshare.do?link=http://www.zengxiaohan.com{% url 'data:content' data.slug %}"> <img src="{% static 'home/assets/renren-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="http://service.weibo.com/share/share.php?url=http://www.zengxiaohan.com{% url 'data:content' data.slug %}&appkey=&title={{ data.title }}&pic={{ data.image }}&ralateUid=&language=zh_cn"> <img src="{% static 'home/assets/weibo-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="https://www.facebook.com/sharer/sharer.php?u=http://www.zengxiaohan.com{% url 'data:content' data.slug %}&display=popup"> <img src="{% static 'home/assets/facebook-logo-dark.png' %}" class="social_network_logo small"/> </a>
					<a href="https://twitter.com/intent/tweet?text=@XiaohanZeng {{ data.title }}&url=http://www.zengxiaohan.com{% url 'data:content' data.slug %}"> <img src="{% static 'home/assets/twitter-logo-dark.png' %}" class="social_network_logo small"/> </a>
				</div>
			</div>
			<div class="data-svg"></div>
			<div class="data-btn"></div>
			<div class="data-body">
				<p id="data-body">
					{{ data.body_html|safe }}
				</p>
				{% if data.code %}
				<p id="data-script">
					{{ data.code|safe }}
				</p>
				{% endif %}
			</div>
			<div class="data-comments" id="disqus_thread"></div>
		</div>
		<noscript>
			Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
		</noscript>
	</div>
</div>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
{% endif %}
{% endblock %}
{% block scripts %}
<script type="text/javascript">
	var disqus_shortname = 'zengxiaohan';
	(function() {
		var dsq = document.createElement('script');
		dsq.type = 'text/javascript';
		dsq.async = true;
		dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	})(); 
</script>
<script src="http://yandex.st/highlightjs/8.0/highlight.min.js"></script>
<script>
	$(document).ready(function() {
		$('pre').each(function(i, e) {
			hljs.highlightBlock(e);
		});
	}); 
</script>
{% endblock %}

mysite/mysite/data/templates/data/data_index.html
{% extends "base_index.html" %}
{% load staticfiles %}
{% block extralinks %}
{% endblock %}

{% block content %}
<div class="masthead masthead-small">
	<div class="container banner">
		<h1 class="lead"> 数据 </h1>
		<h2> 以及隐藏在数据背后的故事 </h2>
	</div>
</div>
{% if list_datas %}
<div class="container">
	<!-- <div class="pagination">
	<span class="step-links"> {% if list_datas.has_previous %} <a href="?page={{ list_datas.previous_page_number }}"> previous </a> {% endif %} <span class="current"> Page {{ list_datas.number }} of {{ list_datas.paginator.num_pages }} </span> {% if list_datas.has_next %} <a href="?page={{ list_datas.next_page_number }}"> next </a> {% endif %} </span>
	</div> -->

	{% for data in list_datas %}
	<div class="data-index">
		<div class="row">
			<div class="col-sm-6">
				<div>
					<a href="{% url 'data:content' data.slug %}"><h1>{{ data.title }}</h1></a>
				</div>
				<p>
					{{ data.pub_date }}
				</p>
				<div class="row data-label-share">
					<div class="col-sm-6">
						{% with categories=data.categories.all %}
						{% if categories %}
						{% for category in categories %}
						<span class="label-primary" href="#"> {{ category.title }} </span>
						{% endfor %}
						{% else %}
						<span class="label" href="#"> 无分类 </span>
						{% endif %}
						{% endwith %}
					</div>
					<div class="col-sm-6 pull-right">
						<a href="http://share.renren.com/share/buttonshare.do?link=http://www.zengxiaohan.com{% url 'data:content' data.slug %}"> <img src="{% static 'home/assets/renren-logo-dark.png' %}" class="social_network_logo small"/> </a>
						<a href="http://service.weibo.com/share/share.php?url=http://www.zengxiaohan.com{% url 'data:content' data.slug %}&appkey=&title={{ data.title }}&pic={{ data.image }}&ralateUid=&language=zh_cn"> <img src="{% static 'home/assets/weibo-logo-dark.png' %}" class="social_network_logo small"/> </a>
						<a href="https://www.facebook.com/sharer/sharer.php?u=http://www.zengxiaohan.com{% url 'data:content' data.slug %}&display=popup"> <img src="{% static 'home/assets/facebook-logo-dark.png' %}" class="social_network_logo small"/> </a>
						<a href="https://twitter.com/intent/tweet?text=@XiaohanZeng {{ data.title }}&url=http://www.zengxiaohan.com{% url 'data:content' data.slug %}"> <img src="{% static 'home/assets/twitter-logo-dark.png' %}" class="social_network_logo small"/> </a>
					</div>
				</div>
				<div class="data-tease">
					<p>
						{{ data.tease }}
					</p>
				</div>
				<a class="btn btn-primary btn-large" href="{% url 'data:content' data.slug %}"> 查看 </a>
			</div>
			<div class="col-sm-4">
				{% if data.image %}
				<img src="{{ MEDIA_URL }}{{ data.image }}" class="data-tease-image"/>
				{% endif %}

			</div>
		</div>
	</div>
	{% endfor %}
	{% else %}
	<li>
		No datas are available.
	</li>
	{% endif %}
</div>
{% endblock %}
{% block scripts %}
<script src="{% static 'home/js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'home/js/imagesloaded.pkgd.min.js' %}"></script>
<script type='text/javascript'>
	var $container = $('#masonry-content');
	// Resolve image loading issue
	$container.imagesLoaded(function() {
		$container.masonry({
			//columnWidth:200,
			itemSelector : '.item'
		});
	}); 
</script>
{% endblock %}