mysite/blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^(?P<blog_slug>[-\w]+)/$', views.content, name='content'))

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from mysite.blog.models import Blog, Category
from filebrowser.sites import site
import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
#    url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'mysite.home.views.homepage', name="home"),
    url(r'^blogs/', include('mysite.blog.urls', namespace="blog")),
    url(r'^data/', include('mysite.data.urls', namespace="data")),
    url(r'^wedding/', 'mysite.wedding.views.view_wedding', name='wedding'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/home/views.py
from django.shortcuts import render_to_response
from django.shortcuts import render, get_object_or_404
from datetime import date
from blog.models import Blog, Category

def homepage(request):
    current_date = date.today()
    highlighted_blogs = [blog for blog in Blog.objects.all() if blog.highlight == True]
    return render(request, 'home/home.html',
                  {'current_date':current_date,
                   'highlighted_blogs':highlighted_blogs})

mysite/mysite/home/views.py
from django.shortcuts import render_to_response
from django.shortcuts import render, get_object_or_404
from datetime import date
from mysite.blog.models import Blog, Category
from mysite.data.models import Data, DataCategory

def homepage(request):
    current_date = date.today()
    highlighted_blogs = [blog for blog in Blog.objects.all()
                         if blog.highlight == True and blog.is_public == True]
    highlighted_data = [data for data in Data.objects.all()
                        if data.highlight == True and data.is_public == True]
    highlighted_posts = highlighted_blogs + highlighted_data
    highlighted_posts.sort(key=lambda x:x.pub_date, reverse=True)
    post_urls, post_types = {}, {}
    for post in highlighted_posts:
        if isinstance(post, Blog) == True:
            post_urls[post.slug] = 'blogs/' + post.slug
            post_types[post.slug] = 'blog'
        elif isinstance(post, Data) == True:
            post_urls[post.slug] = 'data/' + post.slug
            post_types[post.slug] = 'data'
    return render(request, 'home/home.html',
                  {'current_date':current_date,
                   'highlighted_posts':highlighted_posts,
                   'post_urls':post_urls,
                   'post_types':post_types})

mysite/mysite/home/templates/home/home.html
{% extends "base.html" %}
{% load home_tags %}
{% load staticfiles %}

{% block content %}
<!-- Main page starts from here -->
<div class="header">
	<div class="row container">
		<div class="col-lg-5">
			<h5 class="h5 small text">泛覽周王傳，流觀山海圖。俯仰終宇宙，不樂復何如。</h5>
		</div>
		<!-- <div class="col-lg-4">
		<h4>欢迎来到曾笑寒的个人网站.</h4>
		</div> -->
		<div class="col-lg-5 pull-right">
			<h5 class="h5 small text"> {% if current_date %}
			今天是 {{current_date}}
			{% endif %} </h5>
		</div>
	</div>
</div>

<!-- Carousel -->
<div id="myCarousel" class="carousel slide carousel-fade">
	<!-- Indicators -->
	<ol class="carousel-indicators">
		<li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		<li data-target="#myCarousel" data-slide-to="1"></li>
		<li data-target="#myCarousel" data-slide-to="2"></li>
		<li data-target="#myCarousel" data-slide-to="3"></li>
		<li data-target="#myCarousel" data-slide-to="4"></li>
	</ol>
	<div class="carousel-inner">
		{% for post in highlighted_posts %}
		{% if forloop.first %}
		<div class="item active">
			{% else %}
			<div class="item">
				{% endif %}
				<div class="carousel-background" style="background-image:url('{{ MEDIA_URL }}{{ post.image }}')">
					<div class="container">
						<div class="carousel-caption">
							<div class="carousel-caption-background">
								<div class="carousel-caption-content">
									<p class="post-type">
										{% if post_types|get_item:post.slug == 'blog' %}
										博文
										{% elif post_types|get_item:post.slug == 'data' %}
										数据
										{% endif %}
									</p>
									<h1 class="post-caption">{{ post.title }}</h1>
									<p class="post-tease">
										{{ post.tease }}
									</p>
									<p>
										<a class="btn btn-primary btn-large" href="{{post_urls|get_item:post.slug}}">
										{% if post_types|get_item:post.slug == 'blog' %}
										阅读
										{% elif post_types|get_item:post.slug == 'data' %}
										查看
										{% endif %}</a>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		<a class="left carousel-control" href="#myCarousel" data-slide="prev"></a>
		<a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
	</div><!-- /.carousel -->

	<!-- Wrap the rest of the page in another container to center all the content. -->
	<div class="content">
		<div class="content-background marketing">
			<div class="content-block marketing">
				<div class="container marketing">
					<!-- Three columns of text below the carousel -->
					<div class="row">
						<div class="col-lg-5">
							<div class="marketing-header">
								<h1>欢迎来到曾笑寒的个人主页</h1>
								<h4>随便逛逛吧 也许有你感兴趣的话题哦</h4>
							</div>
						</div>
						<div class="col-lg-2">
							<a href="#writing">
							<div class="img-wrapper">
								<img src="{% static 'home/assets/image-pen.png' %}" height="100" width="100"/>
							</div> <h1>文字</h1> <h4> 以笔录事 以文抒情 </h4> </a>
						</div><!-- /.col-lg-4 -->
						<div class="col-lg-2">
							<a href="#data">
							<div class="img-wrapper">
								<img src="{% static 'home/assets/image-gear.png' %}" height="100" width="100"/>
							</div> <h1>研究</h1>
							<div class="text-wrapper">
								<h4>宇宙洪荒 何其有竭</h4>
							</div></a>
						</div><!-- /.col-lg-4 -->
						<div class="col-lg-2">
							<a href="#travel">
							<div class="img-wrapper">
								<img src="{% static 'home/assets/image-camera.png' %}" height="100" width="100"/>
							</div> <h1>光影</h1>
							<div class="text-wrapper">
								<h4> 风轻云淡 且行且观 </h4>
							</div></a>
						</div><!-- /.col-lg-4 -->
					</div><!-- /.row -->
				</div>
			</div>
		</div><!-- /.class="container marketing" -->

		<div class="content-background" id="self-intro">
			<div class="content-block">
				<div class="container featurette">
					<div class="row">
						<div class="text-wrapper">
							<h2 class="featurette-heading">{ 一名纯正的理工科男生 } <span class="text-muted"># 兼具点文艺气质</span></h2>
							<p class="lead">
								['科学'，'文学'，'历史'，'文化'] 都是我感兴趣的话题
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="content-background"  id="writing">
			<div class="content-block">
				<div class="container featurette">
					<div class="row">
						<div class="text-wrapper">
							<h2 class="featurette-heading"> 文字 <span class="text-muted">| 纸墨挥成碧落天 </span></h2>
							<p class="lead">
								阅读与写作乃是我平生两大乐趣。创造属于自己的世界是一件神奇的事情！
							</p>
							<a href="{% url 'blog:index' %}">
							<p class="btn btn-primary btn-large">
								阅读
							</p> </a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="content-background" id="data">
			<div class="content-block">
				<div class="container featurette light">
					<div class="row">
						<div class="text-wrapper">
							<h2 class="featurette-heading light"> 数据 <span class="text-muted">| 两仪八卦衍乾坤 </span></h2>
							<p class="lead">
								大数据时代又是一番好光景。浩如烟海的数据下隐藏着许多故事哦！
							</p>
							<a href="{% url 'data:index' %}">
							<p class="btn btn-primary btn-large">
								查看
							</p></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="content-background"  id="travel">
			<div class="content-block">
				<div class="container featurette">
					<div class="row">
						<div class="text-wrapper">
							<h2 class="featurette-heading"> 旅行 <span class="text-muted">| 星驰原野路漫漫 </span></h2>
							<p class="lead">
								指端上的历史，舌尖上的文化。有什么比得上海螺沟冰川上的一碗泡面，加勒比海上的一杯奶茶？
							</p>
							<p class="btn btn-primary btn-large">
								建设中
							</p>
						</div>
					</div>
				</div><!-- /.class="container featurette" -->
			</div>
		</div>

		<div class="content-background">
			<div class="content-block" id="contact">
				<div class="contact">
					<div>
						<h1>联 系</h1>
					</div>
					<div class="row">
						<div class="col-lg-3">
							<a href="http://www.renren.com/2071260410/profile">
							<div class="contact-img">
								<img src="{% static 'home/assets/renren-logo-dark.png' %}" class="social_network_logo" />
							</div>
							<p class="btn btn-primary">
								人人
							</p> </a>
						</div>
						<div class="col-lg-3">
							<a href="http://weibo.com/u/2649633623">
							<div class="contact-img">
								<img src="{% static 'home/assets/weibo-logo-dark.png' %}" class="social_network_logo"/>
							</div>
							<p class="btn btn-primary" >
								微博
							</p></a>
						</div>
						<div class="col-lg-3">
							<a  href="https://www.facebook.com/xiaohan.zeng.3">
							<div class="contact-img">
								<img src="{% static 'home/assets/facebook-logo-dark.png' %}" class="social_network_logo"/>
							</div>
							<p class="btn btn-primary">
								Facebook
							</p></a>
						</div>
						<div class="col-lg-3">
							<a href="https://twitter.com/XiaohanZeng">
							<div class="contact-img">
								<img src="{% static 'home/assets/twitter-logo-dark.png' %}" class="social_network_logo"/>
							</div>
							<p class="btn btn-primary">
								Twitter
							</p></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!-- End of main page -->
{% endblock %}